### ISSUE TITLE
[macOS 12.x] Extension doesn't load

### ISSUE THREAD

**Issue by Alex-Pie** [PreMiD/Extension-Safari#3]
Hello, I just installed the new **beta** profile for **macOS 12** that was released today after Apple's World Wide Developers Conference, and I've found PreMiD to be completely muted in the presence features that I've had running on my Safari extension on the previous version of macOS (**Big Sur 11.0**) with a MacBook Air running on an **M1** processor. I believe this is just a matter of this beta being released so early and that this is probably the same story with a lot of other extensions for Safari as of right now. The PreMiD extension _does_ seem to work on **Google Chrome** tho, even on the new software, so I think this is just a Safari thing overall. Thought it would be helpful to let the devs know tho!

**Comment by ririxidev** [comment]
Just to be sure; Don't expect me to fix it fast since it's still Developer Beta that has been released 1 day ago and has many many bugs according to macOS Changelog website. I will look into it, but like I said, it's not priority for me.

**Comment by ririxidev** [comment]
Okay so, extension should work fine normally since it works for me but just it exceeds the storage quota somehow?
I need to check it tho.
![image](https://user-images.githubusercontent.com/9348108/121214156-26114580-c87f-11eb-803a-e123fd10f2a1.png)

**Comment by EncryptedDev** [comment]
Heya, many months have past and macOS Monterey is nearing it's public release I suspect - seems like the volume of bugs has significantly decreased too. With that being said, I cannot reproduce such issue; can you?
