### ISSUE TITLE
PreMID

### ISSUE THREAD

**Issue by Elinjohansson1970** [PreMiD/Extension-Safari#4]
Hi! Premid is 10/10 good, bit i have no Idea how i can download the last version? can someone help me with that? i´m not so good with premid and i´m new with that. so i´m glad if someone can help me and download the last version 2.2.4!

**Comment by Slowlife01** [comment]
Hi uh.. Do you have it downloaded now?

**Comment by EncryptedDev** [comment]
Hello! Sorry for the prolongued response time here; we don't usually use our repositories for general questions. In future, you should contact Support via [our Discord](https://discord.premid.app).

Regardless, if you still need the download link, you can find it on the Releases page of the repository or [here](https://github.com/PreMiD/Extension-Safari/releases/tag/v2.2.4)
