### ISSUE TITLE
[macOS 11.x] Missing header 

### ISSUE THREAD

**Issue by vxvrq** [PreMiD/Extension-Safari#5]
whenever i open up a site supported by premid it doesnt show up on my status and when I click on the premid extention my discord name and profile picture and all of that doesnt show up on there? im asuming my discord isnt connected so how would i be able to fix that?

**Comment by EncryptedDev** [comment]
Unable to reproduce, please provide me your environmental factors:
```
macOS version:
Safari version:
```

**Comment by vxvrq** [comment]
macOS: big sur 

safari: 15.0

**Comment by EncryptedDev** [comment]
Send a screenshot of your extenion's console please

**Comment by vxvrq** [comment]
how can I find my extensions console?

**Comment by vxvrq** [comment]
<img width="292" alt="Screen Shot 2022-01-21 at 12 39 48 AM" src="https://user-images
<img width="789" alt="Screen Shot 2022-01-21 at 12 44 04 AM" src="https://user-images.githubusercontent.com/91394670/150472733-ce9c42a9-0bf5-4443-8aa9-48ff81cc05af.png">
.githubusercontent.com/91394670/150472721-18a97d79-a836-4100-88b6-78653f36f549.png">

**Comment by vxvrq** [comment]
<img width="292" alt="Screen Shot 2022-01-21 at 12 39 48 AM" src="https://user-images.githubusercontent.com/91394670/150472818-620ec4d7-484f-462e-bb58-382cd7ddb267.png">
<img width="789" alt="Screen Shot 2022-01-21 at 12 44 04 AM" src="https://user-images.githubusercontent.com/91394670/150472831-797aaaab-a1b0-46d0-97ea-b9827cdee114.png">

**Comment by EncryptedDev** [comment]
Duplicate of #6
